# Generated by Django 3.0.4 on 2020-06-06 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seapp', '0004_auto_20200606_1726'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
